Views
Peter1907/my-blog pull request #6
Opened 2023-01-25 21:43 UTC by Peter1907

Hello, dear code reviewer!

### In this branch, I've implemented the following:

- Updated the actions inside the user & post controller to include the instance variables needed
- Updated the index & show views to include the required info for both the user & post controllers.

Let me know if there's anything to be modified or improved.
Thank you so much for your time & effort.

2023-01-25 22:32 UTC, Munsa1 requested changes
Hi @Peter1907, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Passing Linters :heavy_check_mark: 
Correct GitHub Flow :heavy_check_mark: 
Descriptive ReadMe File :heavy_check_mark: 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-25 22:32 UTC, Munsa1 commented on app/views/users/index.html.erb
> +  </div>
- [ ] Kindly follow the given design for the `users` page as this is a requirement. This means following the layout of components as is in the given wireframes

Given design
![image](https://user-images.githubusercontent.com/81932478/214704250-39c92e46-3f19-471f-adbe-bab89ef2544c.png)

Your design
![image](https://user-images.githubusercontent.com/81932478/214704391-d139c613-b482-46f8-9332-88c6d3d3544c.png)

2023-01-25 22:32 UTC, Munsa1 commented on app/views/users/show.html.erb
> +        <p><%= post.text %></p>
- [ ] Kindly follow the given wireframe template for each user, this includes layout of components on the page as this is a requirement.

Given design
![image](https://user-images.githubusercontent.com/81932478/214705363-5e5c454f-9067-48b7-bf7e-de1cbc201ef6.png)

Your design
![image](https://user-images.githubusercontent.com/81932478/214705633-323a7e2b-4bc1-411d-817c-aed0b8eff9af.png)

2023-01-25 22:32 UTC, Munsa1 commented on app/views/posts/show.html.erb
> +</div>
- [ ] Again here, kindly follow the given design, this includes the border, positioning and layout of components as this is a requirement

Given wireframe
![image](https://user-images.githubusercontent.com/81932478/214706543-f0dfcf07-15d2-4ff6-a7f6-cfda834bac3d.png)

Your design
![image](https://user-images.githubusercontent.com/81932478/214706676-34265e53-8c30-40b0-8834-906d9f3c87da.png)

2023-01-26 16:54 UTC, KayLemba approved these changes
[# STATUS: APPROVED :green_circle: :clap: 

Hello  @Peter1907       , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: aa
Congratulations! 🎉 

HIGHLIGHTS:

- [x]  Your repo is professional 
- [x] Descriptive P.R








 








Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 



![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._]

2023-01-26 17:08 UTC, merged